# Generated by Django 6.1.1 on 2026-09-12 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('INTERVIEW', 'Interview'), ('LINKEDIN', 'LinkedIn'), ('OTHER', 'Other')], max_length=20)),
                ('date', models.DateTimeField()),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='applications.jobapplication')),
            ],
        ),
    ]
