# Generated by Django 6.1.1 on 2026-09-13 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_communication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='communication',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='follow_up_date',
            new_name='reminder_date',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='logo_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reminder_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_customization',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='communication',
            name='communication_type',
            field=models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('interview', 'Interview'), ('offer_received', 'Offer Received'), ('rejection', 'Rejection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='communication',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='communication',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communication',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('SAVED', 'Saved'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=30),
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('summary', 'Summary'), ('experience', 'Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects')], max_length=30)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='applications.resume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
