export const SAMPLE_APPLICATIONS = [
  {
    id: "app-1",
    company: "Stripe",
    position: "Senior Frontend Engineer",
    url: "https://stripe.com/jobs",
    location: "San Francisco, CA",
    salary: "$185,000 – $230,000",
    dateApplied: "2026-08-14",
    status: "interview",
    notes: "Had a great first call with the hiring manager. Strong focus on TypeScript and React performance. Need to review distributed systems basics before the next round.",
    reminderDate: "2026-09-15",
    reminderNote: "Send thank-you follow-up after technical interview",
    logoColor: "#635BFF",
    tags: ["fintech", "remote-friendly", "strong-comp"],
    resumeCustomization: "Emphasize performance optimization work at previous company. Add the metrics from the dashboard rebuild (40% load time reduction). Highlight TypeScript experience in summary.",
    communications: [
      {
        id: "c1-1",
        date: "2026-08-20",
        type: "email",
        subject: "Application received – Senior Frontend Engineer",
        body: "Thank you for applying to Stripe. We've reviewed your application and would love to schedule a 30-minute intro call with a member of our recruiting team.",
      },
      {
        id: "c1-2",
        date: "2026-08-27",
        type: "call",
        subject: "Recruiter screen with Jamie Torres",
        body: "Great conversation. Jamie mentioned the role has 2 more interview rounds: a technical screen and a system design + values interview. Timeline is ~3 weeks.",
      },
      {
        id: "c1-3",
        date: "2026-09-05",
        type: "interview",
        subject: "Technical interview – live coding (90 min)",
        body: "Two problems: one on tree traversal, one on debouncing with React. Felt confident on both. Interviewer was Dan L. from the payments team.",
      },
    ],
  },
  {
    id: "app-2",
    company: "Linear",
    position: "Product Designer",
    url: "https://linear.app/careers",
    location: "Remote",
    salary: "$150,000 – $180,000",
    dateApplied: "2026-08-01",
    status: "offer",
    notes: "Received offer on Sept 3rd. Deadline to decide is Sept 17th. Need to compare against Stripe outcome.",
    reminderDate: "2026-09-16",
    reminderNote: "Deadline to accept/decline Linear offer tomorrow!",
    logoColor: "#5E6AD2",
    tags: ["design-tools", "remote", "top-choice"],
    resumeCustomization: "Lead with design systems work. Include Figma plugin project as a standalone project entry. Remove older brand/print work.",
    communications: [
      {
        id: "c2-1",
        date: "2026-08-08",
        type: "email",
        subject: "Interview invitation – Product Designer",
        body: "Hi, we'd love to move forward with a portfolio review and design exercise. Please send your portfolio and we'll find a time.",
      },
      {
        id: "c2-2",
        date: "2026-08-19",
        type: "interview",
        subject: "Portfolio review + design exercise debrief",
        body: "Went really well. The team loved the design systems work. Karri asked thoughtful questions about trade-offs. Two-hour session.",
      },
      {
        id: "c2-3",
        date: "2026-09-03",
        type: "offer_received",
        subject: "Offer letter – Product Designer",
        body: "Offer: $168,000 base + equity (0.15% over 4yr cliff). $5k signing bonus. Start date flexible. Health, dental, vision fully covered. $3k/yr learning stipend.",
      },
    ],
  },
  {
    id: "app-3",
    company: "Vercel",
    position: "Staff Software Engineer",
    url: "https://vercel.com/careers",
    location: "Remote",
    salary: "$200,000 – $260,000",
    dateApplied: "2026-09-01",
    status: "applied",
    notes: "Applied via referral from a former colleague. Strong alignment with Next.js work I've done. Waiting for initial response.",
    reminderDate: "2026-09-22",
    reminderNote: "Follow up if no response by this date",
    logoColor: "#000000",
    tags: ["infra", "remote", "referred"],
    resumeCustomization: "Open with Next.js and edge runtime experience. Add details about the CDN optimization project. Quantify deployment frequency improvements.",
    communications: [],
  },
  {
    id: "app-4",
    company: "Notion",
    position: "UX Designer, Editor",
    url: "https://notion.so/careers",
    location: "New York, NY",
    salary: "$140,000 – $175,000",
    dateApplied: "2026-08-22",
    status: "phone_screen",
    notes: "Recruiter screen scheduled for Sept 13. The role is focused on the block editor experience. Brush up on their recent redesign.",
    reminderDate: "2026-09-13",
    reminderNote: "Recruiter screen at 11am PT — check calendar invite",
    logoColor: "#000000",
    tags: ["productivity", "nyc", "design"],
    resumeCustomization: "Focus on rich text editor and content creation tool experience. Add the collaborative editing project. Include mention of Notion as a daily-use tool.",
    communications: [
      {
        id: "c4-1",
        date: "2026-09-04",
        type: "email",
        subject: "Next steps – UX Designer application",
        body: "Hi! We'd like to schedule a 30-minute phone screen to learn more about your background. Does next week work for you?",
      },
    ],
  },
  {
    id: "app-5",
    company: "Figma",
    position: "Design Systems Designer",
    url: "https://figma.com/careers",
    location: "San Francisco, CA",
    salary: "$160,000 – $200,000",
    dateApplied: "2026-07-15",
    status: "rejected",
    notes: "Made it to final round but didn't get it. Feedback: needed more experience with token architecture at scale. Good learning for future apps.",
    reminderDate: "",
    reminderNote: "",
    logoColor: "#7C5CFC",
    tags: ["design-tools", "dream-job"],
    resumeCustomization: "Highlight token infrastructure work. Add the multi-brand theming project details.",
    communications: [
      {
        id: "c5-1",
        date: "2026-07-25",
        type: "email",
        subject: "Application update – Design Systems Designer",
        body: "We'd love to move forward with a portfolio review.",
      },
      {
        id: "c5-2",
        date: "2026-08-10",
        type: "interview",
        subject: "Final round – panel interview (3 hrs)",
        body: "Met with 4 team members. Great conversations but the last segment on token architecture felt weak.",
      },
      {
        id: "c5-3",
        date: "2026-08-18",
        type: "rejection",
        subject: "Update on your Figma application",
        body: "After careful consideration, we've decided to move forward with another candidate. We were impressed and encourage you to apply again in 6 months.",
      },
    ],
  },
  {
    id: "app-6",
    company: "Anthropic",
    position: "Frontend Engineer, Claude.ai",
    url: "https://anthropic.com/careers",
    location: "San Francisco, CA",
    salary: "$190,000 – $250,000",
    dateApplied: "2026-09-08",
    status: "applied",
    notes: "Super excited about this one. AI product with a focus on safety. Application submitted through their website.",
    reminderDate: "2026-09-29",
    reminderNote: "Follow up if no response in 3 weeks",
    logoColor: "#D4734A",
    tags: ["ai", "sf", "high-priority"],
    resumeCustomization: "Lead with AI product experience. Add the LLM integration project. Emphasize interest in AI safety and thoughtful product design.",
    communications: [],
  },
  {
    id: "app-7",
    company: "Airbnb",
    position: "Design Lead, Homes",
    url: "https://airbnb.com/careers",
    location: "San Francisco, CA",
    salary: "$180,000 – $220,000",
    dateApplied: "2026-08-05",
    status: "interview",
    notes: "2nd round panel coming up. Four interviewers including the VP of Design. Strong culture emphasis — review their design principles before the call.",
    reminderDate: "2026-09-18",
    reminderNote: "Panel interview prep — review Airbnb design principles doc",
    logoColor: "#FF5A5F",
    tags: ["marketplace", "sf", "design-leadership"],
    resumeCustomization: "Emphasize design leadership and cross-functional collaboration. Add team-building accomplishments. Include the B2C product redesign case study.",
    communications: [
      {
        id: "c7-1",
        date: "2026-08-14",
        type: "call",
        subject: "Recruiter intro call",
        body: "Great intro with Maya from recruiting. Role is focused on redesigning the search and discovery experience for Homes.",
      },
      {
        id: "c7-2",
        date: "2026-08-28",
        type: "interview",
        subject: "1st round – hiring manager interview",
        body: "Excellent conversation with the VP of Design. Discussed my approach to leading design in fast-paced orgs. Moving to panel round.",
      },
    ],
  },
  {
    id: "app-8",
    company: "Loom",
    position: "Senior Product Manager",
    url: "https://loom.com/careers",
    location: "Remote",
    salary: "$150,000 – $185,000",
    dateApplied: "2026-07-28",
    status: "withdrawn",
    notes: "Decided to withdraw after learning more about the role scope. The focus was heavily on growth/monetization, not core product.",
    reminderDate: "",
    reminderNote: "",
    logoColor: "#625DF5",
    tags: ["video", "remote", "pm"],
    resumeCustomization: "",
    communications: [
      {
        id: "c8-1",
        date: "2026-08-04",
        type: "email",
        subject: "Moving forward – Product Manager role",
        body: "We'd love to schedule an intro call. Please use the link below to pick a time.",
      },
    ],
  },
];

export const SAMPLE_RESUME = {
  name: "Test",
  email: "testguy@gmail.com",
  phone: "(415) 555-0142",
  location: "Test Location",
  linkedin: "linkedin.com/in/testguy",
  github: "github.com/testguy",
  website: "testguy.com",
  sections: [
    {
      id: "s-summary",
      title: "Summary",
      type: "summary",
      content:
        "Senior product designer and frontend engineer with 7+ years building design systems, developer tools, and consumer products. Passionate about the intersection of engineering and design — I write TypeScript daily and prototype in Figma. Previously at Atlassian and Dropbox. I thrive in small, autonomous teams working on complex technical problems.",
    },
    {
      id: "s-exp",
      title: "Experience",
      type: "experience",
      content: `**Senior Product Designer & Frontend Engineer — Craft Co.** | 2023 – Present
Led the redesign of the core editor, reducing task completion time by 34%. Built a multi-brand token system serving 4 product lines. Shipped the collaborative multiplayer prototype from 0→1 in 6 weeks.

**Product Designer — Dropbox** | 2021 – 2023
Owned the Dropbox Paper redesign: new block editor, real-time collaboration indicators, and mobile offline experience. Worked directly with engineering to ship high-fidelity interactions.

**UI Engineer — Atlassian** | 2019 – 2021
Built components for Atlassian Design System (ADS). Drove adoption from 12 to 38 product teams. Maintained accessibility to WCAG 2.1 AA standard across all tokens and components.`,
    },
    {
      id: "s-edu",
      title: "Education",
      type: "education",
      content: `**B.S. Computer Science, Minor in Visual Arts — UC Berkeley** | 2015 – 2019
Graduated with honors. Senior thesis: "Designing for Continuity in Collaborative Creative Tools."`,
    },
    {
      id: "s-skills",
      title: "Skills",
      type: "skills",
      content: `**Design:** Figma, Framer, Prototyping, Design Systems, Token Architecture, User Research, Accessibility (WCAG 2.1)
**Engineering:** TypeScript, React, Next.js, CSS/Tailwind, Node.js, GraphQL, Storybook, Playwright
**Tools:** Linear, Notion, GitHub, Vercel, Datadog, Segment`,
    },
    {
      id: "s-projects",
      title: "Projects",
      type: "projects",
      content: `**Tokens CLI** — Open-source tool for managing design tokens across codebases. 1,400+ GitHub stars.
**Figma Context MCP** — MCP server that streams Figma design context to LLM agents. Featured in Figma newsletter.
**Palette** — Color palette generator with WCAG contrast checking. Used by 2,000+ designers monthly.`,
    },
  ],
};
